config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get('/home', to: 'welcome#home')
  get('/about', to: 'welcome#about')
  get('/contact_us', to: 'welcome#contact_us')
  post('/thank_you', to: 'welcome#thank_you')

  #bill splitter
  get '/bill_splitter', to: 'bill_splitter#new'
  post '/calculate_split', to: 'bill_splitter#create'

  # Session Routes
  resource :session, only: [:new, :create, :destroy]

  
  resources :users, only: [:new, :create]
  # RESTful Product Routes
  #  get '/products/new', to: 'products#new', as: :new_product
  #  post '/products', to: 'products#create'
  #  get '/products/:id', to: 'products#show', as: :product
  #  get '/products', to: 'products#index'
  #  delete '/products/:id', to: 'products#destroy'
  #  get '/products/:id/edit', to: 'products#edit', as: :edit_product
  #  patch '/products/:id', to: 'products#update'
  resources :products do
    resources :reviews, only: [:create, :destroy]
  end


end

app/views/shared/_flash_messages.html.erb
<div class='container'>
  <% flash.each do |type, message| %>
    <div class='shadow-lg p-3 mb-5 bg-<%= type %> rounded'>
      <%= message %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<%# mb-5 is bootstrap for setting the margin bottom to size 5 https://getbootstrap.com/docs/4.4/utilities/spacing/ %>
<nav class='navbar navbar-light bg-light mb-5'>
  <ul>
    <span class='navbar-brand mb-0 h1'>Amazing Amazon 💰🤑
      <%= link_to 'Home', home_path, class: 'nav-item' %>
      |
      <%= link_to 'About', about_path, class: 'nav-item' %>
      |
      <%= link_to 'Contact Us', contact_us_path, class: 'nav-item' %>
      |
      <%= link_to 'Bill Splitter', bill_splitter_path, class: 'nav-item' %>
      |
      <%= link_to 'View Products', products_path, class: 'nav-item' %>
    </span>
  </ul>
  <div>
    <% if user_signed_in? %>
      <span class='text-muted mr-3'>Hello, <%= current_user.full_name %></span>
      <%= link_to "Log Out", session_path, method: :delete, class: 'btn btn-danger' %>
    <% else %>
      <%= link_to "Log In", new_session_path, class: 'btn btn-success' %>
    <% end %>
  </div>
</nav>