config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get('/home', to: 'welcome#home')
  get('/about', to: 'welcome#about')
  get('/contact_us', to: 'welcome#contact_us')
  post('/thank_you', to: 'welcome#thank_you')

  #bill splitter
  get '/bill_splitter', to: 'bill_splitter#new'
  post '/calculate_split', to: 'bill_splitter#create'

  # Session Routes
  resource :session, only: [:new, :create, :destroy]

  
  resources :users, only: [:new, :create]
  # RESTful Product Routes
  #  get '/products/new', to: 'products#new', as: :new_product
  #  post '/products', to: 'products#create'
  #  get '/products/:id', to: 'products#show', as: :product
  #  get '/products', to: 'products#index'
  #  delete '/products/:id', to: 'products#destroy'
  #  get '/products/:id/edit', to: 'products#edit', as: :edit_product
  #  patch '/products/:id', to: 'products#update'
  resources :products do
    resources :reviews, only: [:create, :destroy]
  end


end

app/models/product.rb
class Product < ApplicationRecord
  # A constant is a value that should never change. We use these often to replace hard coded values. That way you can use this constant in multiple areas and if you ever need to change it you'd only need to change it at one place.
  DEFAULT_PRICE = 1 # a ruby convention is to place constants at the top of the file and name them using SCREAMING_SNAKE_CASE
  # rubocop has good guidelines on best practices https://github.com/rubocop-hq/ruby-style-guide
  DEFAULT_HIT_COUNT = 1
  # Potential bug alert: :set_default_sale_price should always be called after :set_default_price otherwise you can end up with a sale price of nil
  # Potential Bug alert: calling :capitalize_title on the after_validation callback will allow products with identical titles to be saved to the database
  before_validation :set_default_price, :set_default_sale_price, :set_default_hit_count, :capitalize_title
  # only invoke this callback if the current environment is development.
  before_destroy :log_delete_details, unless: Proc.new { !Rails.env.development? }

  validates(:title,
    presence: true,
    uniqueness: true,
    exclusion:
      { in: ['apple', 'microsoft', 'sony'],
        message: "%{value} is a reserved title. Please use a different title"
      }
  )
  validates :price, numericality: { greater_than: 0 }
  validates :description, presence: true, length: { minimum: 10 }
  validate :sale_price_less_than_price

  belongs_to :user
  # has_many accepts a scope as a second argument. This scope will make all associated reviews ordered by their updated_at, see the following example:
=begin
  @product = Product.find(params[:id])
  @product.reviews # will be all the associated reviews for this particular product and due to the scope they're all ordered by updated_at
=end

  has_many :reviews, -> { order('updated_at DESC') }, dependent: :destroy 

  # scope(name, body, &block) is a method that will add a class method for retrieving records
  # https://api.rubyonrails.org/classes/ActiveRecord/Scoping/Named/ClassMethods.html#method-i-scope
  # in ruby & rails docks &block means the method accepts a lambda.
  scope(:search, -> (query) { where("title ILIKE?", "%#{query}%") })

  # you can create a class method that does the same thing.

  def self.search_but_using_class_method(query)
    where("title ILIKE?", "%#{query}%")
  end

  def increment_hit_count
    new_hit_count = self.hit_count += 1
    update({ hit_count: new_hit_count })
  end

  def self.get_paginated(search, sort_by_col, current_page, per_page_count)
    where("title ILIKE ? OR description ILIKE ?", "%#{search}%", "%#{search}%").order(Hash[sort_by_col, :desc]).limit(per_page_count).offset(current_page * per_page_count) 
  end

  private

  def set_default_price
    self.price ||= DEFAULT_PRICE
  end

  def capitalize_title
    self.title.capitalize!
  end

  def sale_price_less_than_price
    if self.sale_price > self.price
      errors.add(:sale_price, "sale_price: #{self.sale_price} must be lower than price: #{self.price}")
    end
  end

  def set_default_sale_price
    self.sale_price ||= self.price
  end

  def log_delete_details
    puts "Product #{self.id} is about to be deleted"
  end

  def set_default_hit_count
    self.hit_count ||= DEFAULT_HIT_COUNT
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize!, only: [:edit, :update, :destroy]
  def index
    @products = Product.all.order('created_at DESC')
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new product_params
    @product.user = @current_user
    if @product.save
      render(plain: "Created Product #{@product.inspect}")
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
    @review = Review.new
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update product_params
      redirect_to product_path @product
    else
      render :edit
    end
  end

  def authorize! 
    redirect_to root_path, alert: 'Not Authorized' unless can?(:crud, Product)
  end
  private

  def product_params
    # docs about params.require() https://api.rubyonrails.org/classes/ActionController/Parameters.html#method-i-require
    # docs about .permit() https://api.rubyonrails.org/classes/ActionController/Parameters.html#method-i-permit
    params.require(:product).permit(:title, :description, :price, :sale_price)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<% if @product.errors.present? %>
  <p>
    <%= @product.errors.full_messages.join(', ')%>
  </p>
<% end %>

<%# by default rails forms will submit using XHR/AJAX we'll learn this in the future but for now we want to submit using HTML5 forms so we'll have to set the `local` option to true%>
<%# https://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-form_with %>
<%# form_with uses @product.new_record? to determine if this form should patch or post %>
<%= form_with model: @product, local:true do |f| %>
  <div class='form-group'>
    <%= f.label :title %>
    <%= f.text_field(:title, class: 'form-control', placeholder: 'Product Name')%>
  </div>
  <div class='form-group'>
    <%= f.label :description %>
    <%= f.text_area(:description, class: 'form-control', cols: 50, rows: 5, placeholder: 'Provide Description')%>
  </div>
  <div class='form-group'>
    <%= f.label :price %>
    <%= f.number_field(:price, class: 'form-control', min: 0, placeholder: 'Enter Price', step: :any )%>
  </div>
  <div class='form-group'>
    <%= f.label :sale_price %>
    <%= f.number_field(:sale_price, class: 'form-control', min: 0, placeholder: 'Enter Sale Price', step: :any )%>
  </div>
  <% if @product.new_record? %>
    <%= f.submit("Create", class: 'btn btn-primary') %>
  <% else %>
    <%= f.submit("Update", class: 'btn btn-primary') %>
  <% end %>
<% end %>

app/views/products/edit.html.erb
<div class='shadow-sm p-3 mb-5 bg-white rounded'>
  <h1 class='m-0'>
    <small class='text-muted'>
      Editing: 
    </small>
    <span class='badge badge-pill badge-info'>
      <%= @product.id %>
    </span>
    <%= @product.title %>
  </h1>
</div>
<div class='shadow p-3 mb-5 bg-white rounded'>
  <%= render 'form' %>
</div>

app/views/products/index.html.erb
<div class='row'>
  <div class='col-2'>
  </div>

  <div class='col-10'>
    <div class='list-group'>
      <% @products.each do |product| %>
        <%= link_to product do %>
          <li class='list-group-item'>
            <p><span class='badge badge-light'><%= product.id %></span> <%= product.title %></p>
            <small>Last Updated: <%= time_ago_in_words product.updated_at %></small>
          </li>
        <% end %>
      <% end %>
    </div>
  </div>
</div> 

app/views/products/new.html.erb
<div class='shadow p-3 mb-5 bg-white rounded'>
  <%= render 'form' %>
</div>

app/views/products/show.html.erb
<div class='shadow-sm p-3 mb-5 bg-white rounded overflow-wrap'>
  <div class='clearfix'>
    <h1 class='float-left'>
      <span class='badge badge-pill badge-info'>
        <%= @product.id %>
      </span>
      <%= @product.title %>
    </h1>
    <h1 class='float-right text-center'>
      <% if @product.sale_price.present? && @product.sale_price < @product.price %>
        <span class='badge badge-pill badge-success'><s><%= number_to_currency @product.price %></s></span>
        <span class='badge badge-pill badge-danger'><%= number_to_currency @product.sale_price %></span>
      <% else %>
        <span class='badge badge-pill badge-success'><%= number_to_currency @product.price %></span>
      <% end %>
    </h1>
    
  </div>
  <small class='text-muted'>
    sold by <em><%= @product.user.full_name %></em>
  <small>
  <hr/>
  <p class='shadow-none p-3 rounded'><%= @product.description %></p>
    <% if can? :crud, @product %>
  <div>
    <%# link_to() just creates a anchor tag with the appropriate href. The 3rd argument is a optional options hash which can have a :method key; If a :method key is provided Rails will set a data-method attribute to the a tag and adds some additional javascript to the page which makes the anchor tag use the specified http method instead of the default GET. (Basically Rails Magic) 
    <%# https://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-link_to %>
    <%# passing a value (number/string) to a helper method like `product_path` will return a path with the value appended to the path. Helper paths automatically grab and use the id if it's given a instance %>
    <%= link_to(
      "Delete",
      product_path(@product),
      method: :delete,
      class: 'btn btn-danger',
      data: { confirm: 'are you sure?' },
      )
    %>
    <%= link_to "Edit", edit_product_path(@product), class: 'btn btn-info'%>
  </div>
    <% end %>
</div> 
<p class='text-muted'>Leave a Review :D</p>
<div class='shadow-sm p-3 mb-5 bg-white rounded'>
  <%= form_with model: [@product, @review], local: true do |f| %>
    <div class='form-group'>
      <%= f.label :rating %>
      <%= f.select(:rating, options_for_select(1..5), class: 'form-control' )%>
    </div>
    <div class='form-group'>
      <%= f.label :body %>
      <%= f.text_area(:body, class: 'form-control', placeholder: 'Your thoughts here' )%>
    </div>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

<h2> Here's what people are saying: </h2>

<% @product.reviews.each do |review| %>
  <div class='shadow-sm p-3 mb-1 bg-white rounded'>   
  <%# display_stars is a custom helper method to display stars located in /app/helpers/reviews_helper.rb %>
  <%# all methods defined in any helper file are available in all views :D. We can place complex logic in these helpers to avoid bloating our model. (business logic inside of controller should be kept to a minimum) %>
    <h4>
      <%= display_stars(review) %>
      <p class='font-weight-lighter d-inline-block'>by <%= review.user.full_name %></p>
       <% if can? :crud, review %>
      <%= link_to(
        "Delete",
        product_review_path(@product, review),
        method: :delete,
        class: 'btn btn-danger float-right',
        data: { confirm: 'delete this review?' }
        )
      %>
       <% end %>
    </h4>
    <%# adding styles to .review-body inside of 'app/assets/stylesheets/reviews.scss'. Rails will automatically include stylesheets in controllers if the name of the stylesheet is the same name as the controller %>
    <p class='review-body text-muted'><%= review.body %></p>
  </div>
<% end %>